import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

const BRAND = '#0B3B82';

const content = {
  terms: { title: 'Termos de Uso', sections: [['O papel da Rubli', 'A Rubli Tecnologia LTDA é uma plataforma de intermediação que aproxima Clientes e Prestadores. Não executamos os serviços e não somos empregadores dos prestadores.'], ['Responsabilidades', 'Cliente e Prestador definem diretamente escopo, preço, prazo, materiais e forma de pagamento. O prestador é responsável por habilitação, qualidade, segurança e obrigações de sua atividade.'], ['Uso seguro', 'Não é permitido publicar informações falsas, assediar, discriminar, fraudar, manipular avaliações ou usar a plataforma para atividades ilegais.'], ['Limites legais', 'A Rubli não garante o resultado de serviços de terceiros, sem excluir responsabilidades que a legislação brasileira atribua à própria plataforma.']] },
  privacy: { title: 'Política de Privacidade', sections: [['Dados tratados', 'Podemos tratar dados de cadastro, perfil, demandas, propostas, mensagens, avaliações, localização autorizada, fotos, notificações e registros técnicos de segurança.'], ['Finalidades', 'Usamos dados para operar o app, viabilizar negociações, prestar suporte, proteger contas, prevenir fraude e cumprir obrigações legais.'], ['Compartilhamento', 'Compartilhamos o necessário entre Cliente e Prestador e com fornecedores de infraestrutura e notificações. A Rubli não vende dados pessoais.'], ['Seus direitos', 'Nos termos da LGPD, você pode pedir acesso, correção, informação sobre compartilhamento, portabilidade, eliminação quando aplicável e revogação de consentimento.']] },
} as const;

export function LegalDocumentModal({ document, onClose }: { document: 'terms' | 'privacy' | null; onClose: () => void }) {
  if (!document) return null;
  const item = content[document];
  return <Modal visible animationType="slide" onRequestClose={onClose}><View style={styles.root}><View style={styles.header}><Text style={styles.title}>{item.title}</Text><TouchableOpacity style={styles.close} onPress={onClose}><Text style={styles.closeText}>Fechar</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.version}>Rubli Tecnologia LTDA · Versão 1.0</Text>{item.sections.map(([heading, text]) => <View key={heading} style={styles.card}><Text style={styles.heading}>{heading}</Text><Text style={styles.text}>{text}</Text></View>)}<Text style={styles.footer}>A versão integral dos documentos está disponível à administração do Rubli. Em caso de dúvida ou solicitação sobre seus dados, use Ajuda e suporte.</Text></ScrollView></View></Modal>;
}
const styles = StyleSheet.create({ root:{flex:1,backgroundColor:'#F6F9FE'},header:{backgroundColor:'#FFF',padding:16,borderBottomWidth:1,borderBottomColor:'#E5EAF0',flexDirection:'row',alignItems:'center'},title:{flex:1,color:BRAND,fontSize:23,fontWeight:'900'},close:{backgroundColor:BRAND,borderRadius:11,paddingHorizontal:13,paddingVertical:9},closeText:{color:'#FFF',fontWeight:'800'},content:{padding:18,paddingBottom:42},version:{color:'#718096',marginBottom:13},card:{backgroundColor:'#FFF',borderRadius:15,borderWidth:1,borderColor:'#E0E8F2',padding:16,marginBottom:11},heading:{color:BRAND,fontSize:17,fontWeight:'900',marginBottom:7},text:{color:'#4B5F76',lineHeight:21},footer:{color:'#718096',lineHeight:19,marginTop:8}});
