import { useEffect, useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import type { User } from '@rubli/shared';
import { apiCreateSupportTicket, apiListSupportTickets, type SupportTicket } from '../api/client';

const BRAND = '#0B3B82';
const ACCENT = '#0B66FF';

export function SupportScreen({ user, visible, onClose }: { user: User; visible: boolean; onClose: () => void }) {
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [sending, setSending] = useState(false);
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  async function reload() { try { setTickets(await apiListSupportTickets(user.id)); } catch { setTickets([]); } }
  useEffect(() => { if (visible) reload(); }, [visible, user.id]);
  async function submit() {
    if (!subject.trim() || !message.trim()) return Alert.alert('Complete o chamado', 'Informe o assunto e explique o que aconteceu.');
    setSending(true);
    try { const ticket = await apiCreateSupportTicket({ userId: user.id, userName: user.name, userRole: user.role, subject: subject.trim(), message: message.trim() }); setSubject(''); setMessage(''); await reload(); Alert.alert('Chamado enviado', `Recebemos seu pedido de suporte. Protocolo: ${ticket.id}`); } catch (error) { Alert.alert('Não foi possível enviar', error instanceof Error ? error.message : 'Tente novamente.'); } finally { setSending(false); }
  }
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.root}><View style={styles.header}><Text style={styles.title}>Ajuda e suporte</Text><TouchableOpacity style={styles.close} onPress={onClose}><Text style={styles.closeText}>Fechar</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.help}>Relate um problema com segurança. A administração acompanha o status por aqui.</Text><Text style={styles.label}>Assunto</Text><TextInput value={subject} onChangeText={setSubject} maxLength={120} placeholder="Ex.: Problema em uma negociação" style={styles.input}/><Text style={styles.label}>Descreva o que aconteceu</Text><TextInput value={message} onChangeText={setMessage} maxLength={4000} multiline textAlignVertical="top" placeholder="Inclua o chamado ou a etapa envolvida, se houver." style={[styles.input, styles.message]}/><TouchableOpacity disabled={sending} style={styles.send} onPress={() => submit().catch(() => undefined)}><Text style={styles.sendText}>{sending ? 'Enviando...' : 'Abrir chamado de suporte'}</Text></TouchableOpacity><Text style={styles.historyTitle}>Meus chamados</Text>{tickets.length === 0 ? <Text style={styles.empty}>Você ainda não abriu nenhum chamado.</Text> : tickets.map((ticket) => <View style={styles.ticket} key={ticket.id}><Text style={styles.ticketSubject}>{ticket.subject}</Text><Text style={styles.ticketStatus}>{ticket.status === 'open' ? 'Aberto' : ticket.status === 'in_progress' ? 'Em atendimento' : 'Resolvido'}</Text><Text style={styles.ticketMessage}>{ticket.message}</Text>{(ticket.statusHistory ?? []).map((event, index) => <Text key={`${event.at}-${index}`} style={styles.event}>• {event.status === 'open' ? 'Aberto' : event.status === 'in_progress' ? 'Em atendimento' : 'Resolvido'} em {new Date(event.at).toLocaleString('pt-BR')}</Text>)}</View>)}</ScrollView></View></Modal>;
}
const styles = StyleSheet.create({ root:{flex:1,backgroundColor:'#F6F9FE'},header:{backgroundColor:'#FFF',padding:16,borderBottomWidth:1,borderBottomColor:'#E5EAF0',flexDirection:'row',alignItems:'center'},title:{flex:1,color:BRAND,fontSize:24,fontWeight:'900'},close:{backgroundColor:BRAND,borderRadius:11,paddingHorizontal:13,paddingVertical:9},closeText:{color:'#FFF',fontWeight:'800'},content:{padding:18,paddingBottom:40},help:{color:'#607086',lineHeight:20,marginBottom:18},label:{color:BRAND,fontWeight:'900',marginBottom:7},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#D8E2EF',borderRadius:14,padding:14,marginBottom:16,color:BRAND},message:{minHeight:150},send:{backgroundColor:ACCENT,borderRadius:14,padding:15,alignItems:'center'},sendText:{color:'#FFF',fontWeight:'900'},historyTitle:{color:BRAND,fontWeight:'900',fontSize:19,marginTop:25,marginBottom:10},empty:{color:'#718096',padding:16,backgroundColor:'#FFF',borderRadius:12},ticket:{backgroundColor:'#FFF',borderRadius:15,borderWidth:1,borderColor:'#DCE5F0',padding:14,marginBottom:10},ticketSubject:{color:BRAND,fontWeight:'900',fontSize:16},ticketStatus:{color:ACCENT,fontWeight:'900',marginTop:5},ticketMessage:{color:'#526174',lineHeight:19,marginTop:7},event:{color:'#718096',fontSize:12,marginTop:6}});
