import { useEffect, useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import type { Conversation, Demand, Proposal, Rating, User } from '@rubli/shared';
import { getConversations, getDemands, getProposals, saveConversations, saveDemands, saveProposals } from '../storage/localStore';
import { getRatings } from '../profile/profileStore';
import { ChatScreen } from './ChatScreen';
import { PublicProfileScreen } from './PublicProfileScreen';
const BRAND='#081B33'; const ACCENT='#F28C28';
interface Props{user:User;profiles:User[];onClose:()=>void;}
const id=(p:string)=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`; const money=(v:number)=>`R$ ${v.toFixed(2).replace('.',',')}`;
const isOperationalDemand=(d:Demand)=>!['completed','cancelled'].includes(d.status);
export function TestNegotiationsScreen({user,profiles,onClose}:Props){
 const [demands,setDemands]=useState<Demand[]>([]),[proposals,setProposals]=useState<Proposal[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[ratings,setRatings]=useState<Rating[]>([]),[activeConversation,setActiveConversation]=useState<Conversation|null>(null),[profileTarget,setProfileTarget]=useState<User|null>(null);
 async function reload(){const [d,p,c,r]=await Promise.all([getDemands(),getProposals(),getConversations(),getRatings()]);setDemands(d);setProposals(p);setConversations(c);setRatings(r)}
 useEffect(()=>{reload().catch(()=>Alert.alert('Erro','Não foi possível carregar as negociações.'))},[user.id]);
 const myProposals=proposals.filter(p=>p.providerId===user.id); const myDemands=demands.filter(d=>d.requesterId===user.id&&isOperationalDemand(d));
 async function openConversation(demand:Demand,providerId:string){let c=conversations.find(x=>x.demandId===demand.id&&x.customerId===demand.requesterId&&x.providerId===providerId);if(!c){const now=new Date().toISOString();c={id:id('conv'),demandId:demand.id,customerId:demand.requesterId,providerId,createdAt:now,updatedAt:now};const next=[c,...conversations];setConversations(next);await saveConversations(next)}setActiveConversation(c)}
 async function acceptProposal(p:Proposal){const d=demands.find(x=>x.id===p.demandId);if(!d||d.requesterId!==user.id||p.status!=='pending')throw new Error('Proposta inválida.');const now=new Date().toISOString();const updated={...p,status:'accepted' as const,customerConfirmedAt:now};const np=proposals.map(x=>x.demandId===d.id?(x.id===p.id?updated:x.status==='pending'?{...x,status:'rejected' as const}:x):x);const nd=demands.map(x=>x.id===d.id?{...x,status:'negotiating' as const,acceptedProviderId:p.providerId,updatedAt:now}:x);await saveProposals(np);await saveDemands(nd);setProposals(np);setDemands(nd)}
 async function confirmProvider(p:Proposal){if(user.id!==p.providerId||p.status!=='accepted'||!p.customerConfirmedAt)throw new Error('A proposta ainda não foi confirmada pelo cliente.');const now=new Date().toISOString();const np=proposals.map(x=>x.id===p.id?{...x,providerConfirmedAt:now}:x);const nd=demands.map(x=>x.id===p.demandId?{...x,status:'accepted' as const,acceptedProviderId:p.providerId,updatedAt:now}:x);await saveProposals(np);await saveDemands(nd);setProposals(np);setDemands(nd)}
 async function counterProposal(p:Proposal,amount:number,message?:string){if(p.status!=='pending')throw new Error('Só é possível contrapropor uma negociação pendente.');const d=demands.find(x=>x.id===p.demandId);if(!d||(user.id!==d.requesterId&&user.id!==p.providerId))throw new Error('Sem permissão.');const now=new Date().toISOString();const version=Math.max(0,...proposals.filter(x=>x.demandId===d.id).map(x=>x.version??1))+1;const next={id:id('pro'),demandId:d.id,providerId:p.providerId,amount:Math.round(amount*100)/100,message,status:'pending' as const,version,parentProposalId:p.id,offeredBy:user.id===d.requesterId?'customer' as const:'provider' as const,createdAt:now};const np=proposals.map(x=>x.id===p.id?{...x,status:'superseded' as const}:x);np.unshift(next);const nd=demands.map(x=>x.id===d.id?{...x,status:'negotiating' as const,updatedAt:now}:x);await saveProposals(np);await saveDemands(nd);setProposals(np);setDemands(nd)}
 async function startService(d:Demand){if(user.id!==d.acceptedProviderId||d.status!=='accepted')throw new Error('Somente o prestador contratado pode iniciar.');const now=new Date().toISOString();const nd=demands.map(x=>x.id===d.id?{...x,status:'in_progress' as const,startedAt:now,updatedAt:now}:x);await saveDemands(nd);setDemands(nd)}
 async function completeService(d:Demand){if(user.id!==d.acceptedProviderId||d.status!=='in_progress')throw new Error('Somente o prestador contratado pode concluir.');const now=new Date().toISOString();const completed={...d,status:'completed' as const,completedAt:now,updatedAt:now};const nd=demands.map(x=>x.id===d.id?completed:x);await saveDemands(nd);setDemands(nd.filter(isOperationalDemand))}
 if(activeConversation){const d=demands.find(x=>x.id===activeConversation.demandId);const p=proposals.filter(x=>x.demandId===activeConversation.demandId&&x.providerId===activeConversation.providerId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];return <ChatScreen conversation={activeConversation} currentUserId={user.id} otherUserName={user.id===activeConversation.customerId?profiles.find(x=>x.id===activeConversation.providerId)?.name:profiles.find(x=>x.id===activeConversation.customerId)?.name} onAcceptProposal={p?acceptProposal:undefined} onConfirmAgreement={p?confirmProvider:undefined} onCounterProposal={p?counterProposal:undefined} onStartService={d?startService:undefined} onCompleteService={d?completeService:undefined} onBack={()=>{setActiveConversation(null);reload().catch(()=>undefined)}}/>}
 return <View style={styles.container}><View style={styles.header}><View style={styles.headerText}><Text style={styles.title}>Negociações</Text><Text style={styles.subtitle}>{user.role==='provider'?'Suas propostas e conversas':'Suas demandas e propostas recebidas'}</Text></View><TouchableOpacity onPress={onClose} style={styles.closeButton}><Text style={styles.closeText}>Fechar</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}>{user.role==='provider'?(myProposals.filter(p=>{const d=demands.find(x=>x.id===p.demandId);return d&&isOperationalDemand(d)}).length?myProposals.filter(p=>{const d=demands.find(x=>x.id===p.demandId);return d&&isOperationalDemand(d)}).map(p=>{const d=demands.find(x=>x.id===p.demandId);if(!d)return null;const c=profiles.find(x=>x.id===d.requesterId);return <View key={p.id} style={styles.card}><Text style={styles.category}>{d.category}</Text><Text style={styles.cardTitle}>{d.title}</Text><Text style={styles.meta}>{c?.name??'Cliente'} · {money(p.amount)} · {p.status}</Text><TouchableOpacity style={styles.primary} onPress={()=>openConversation(d,user.id).catch(()=>undefined)}><Text style={styles.primaryText}>Conversar</Text></TouchableOpacity></View>}):<Text style={styles.empty}>Você ainda não possui negociações ativas.</Text>):(myDemands.length?myDemands.map(d=><View key={d.id} style={styles.card}><Text style={styles.category}>{d.category}</Text><Text style={styles.cardTitle}>{d.title}</Text>{proposals.filter(p=>p.demandId===d.id).map(p=>{const pr=profiles.find(x=>x.id===p.providerId);return <View key={p.id} style={styles.proposal}><Text style={styles.amount}>{money(p.amount)}</Text><Text style={styles.meta}>{pr?.name??'Prestador'} · {p.status}</Text><View style={styles.actions}>{pr&&<TouchableOpacity style={styles.outline} onPress={()=>setProfileTarget(pr)}><Text style={styles.outlineText}>Ver perfil</Text></TouchableOpacity>}<TouchableOpacity style={styles.outline} onPress={()=>openConversation(d,p.providerId).catch(()=>undefined)}><Text style={styles.outlineText}>Conversar</Text></TouchableOpacity></View></View>)}</View>):<Text style={styles.empty}>Você não possui demandas ativas.</Text>)}</ScrollView>{profileTarget&&<PublicProfileScreen user={profileTarget} ratings={ratings} visible onClose={()=>setProfileTarget(null)}/>}</View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F9FC'},header:{backgroundColor:'#FFF',padding:16,borderBottomWidth:1,borderBottomColor:'#E5EAF0',flexDirection:'row',alignItems:'center'},headerText:{flex:1},title:{color:BRAND,fontSize:24,fontWeight:'900'},subtitle:{color:'#718096',marginTop:3},closeButton:{backgroundColor:BRAND,borderRadius:12,paddingHorizontal:13,paddingVertical:9},closeText:{color:'#FFF',fontWeight:'800'},content:{padding:16,paddingBottom:40},card:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E3E9F0',borderRadius:16,padding:15,marginBottom:12},category:{color:ACCENT,fontWeight:'900'},cardTitle:{color:BRAND,fontSize:18,fontWeight:'900',marginTop:5},meta:{color:'#68778C',marginBottom:7},proposal:{marginTop:10,paddingTop:10,borderTopWidth:1,borderTopColor:'#E8EDF3'},amount:{color:BRAND,fontWeight:'900',fontSize:17},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},primary:{backgroundColor:ACCENT,borderRadius:11,paddingHorizontal:14,paddingVertical:10},primaryText:{color:'#FFF',fontWeight:'900'},outline:{borderWidth:1,borderColor:BRAND,borderRadius:11,paddingHorizontal:14,paddingVertical:9},outlineText:{color:BRAND,fontWeight:'900'},empty:{color:'#718096',textAlign:'center',padding:24}});
