import { StatusBar } from 'expo-status-bar';
import * as Location from 'expo-location';
import { useEffect, useMemo, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import type { ChatMessage, Conversation, Demand, DemandType, Proposal, User, UserRole } from '@rubli/shared';
import { DEMAND_CATEGORIES, distanceKm, isValidCoordinates } from '@rubli/shared';
import { getConversations, getDemands, getMessages, getProposals, getUser, saveConversations, saveDemands, saveMessages, saveProposals, saveUser } from './src/storage/localStore';

const BRAND = '#081B33';
const ACCENT = '#F28C28';
const BG = '#F7F9FC';
const DEFAULT_RADIUS = 10;
const RADIUS_OPTIONS = [5, 10, 20, 50, 100] as const;

type Screen = 'home' | 'create' | 'profile' | 'chat';
const TYPE_LABELS: Record<DemandType, string> = { service: 'Serviço', purchase: 'Compra', delivery: 'Entrega', freight: 'Frete' };

function newId(prefix: string) { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`; }
function money(value?: number) { return typeof value === 'number' ? `R$ ${value.toFixed(2).replace('.', ',')}` : 'Valor aberto'; }
function formatDistance(km: number) { return km < 1 ? `${Math.round(km * 1000)} m` : `${km.toFixed(1).replace('.', ',')} km`; }

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [demands, setDemands] = useState<Demand[]>([]);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [screen, setScreen] = useState<Screen>('home');
  const [activeConversation, setActiveConversation] = useState<Conversation | null>(null);
  const [name, setName] = useState(''); const [role, setRole] = useState<UserRole>('customer');
  const [type, setType] = useState<DemandType>('service'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [budget, setBudget] = useState(''); const [locationLabel, setLocationLabel] = useState(''); const [latitude, setLatitude] = useState<number | undefined>(); const [longitude, setLongitude] = useState<number | undefined>(); const [isUrgent, setIsUrgent] = useState(false);
  const [providerRadius, setProviderRadius] = useState(DEFAULT_RADIUS); const [providerLatitude, setProviderLatitude] = useState<number | undefined>(); const [providerLongitude, setProviderLongitude] = useState<number | undefined>(); const [urgentOnly, setUrgentOnly] = useState(false); const [selectedTypeFilter, setSelectedTypeFilter] = useState<DemandType | 'all'>('all'); const [proposalAmounts, setProposalAmounts] = useState<Record<string, string>>({}); const [proposalMessages, setProposalMessages] = useState<Record<string, string>>({}); const [profileName, setProfileName] = useState('');

  useEffect(() => { Promise.all([getUser(), getDemands(), getProposals(), getConversations(), getMessages()]).then(([storedUser, storedDemands, storedProposals, storedConversations, storedMessages]) => { setUser(storedUser); setDemands(storedDemands); setProposals(storedProposals); setConversations(storedConversations); setMessages(storedMessages); if (storedUser) { setProviderRadius(storedUser.serviceRadiusKm ?? DEFAULT_RADIUS); setProfileName(storedUser.name); } }); }, []);
  const categories = useMemo(() => DEMAND_CATEGORIES[type] as readonly string[], [type]);

  const providerFeed = useMemo(() => { if (!user || user.role !== 'provider') return [] as Array<{ demand: Demand; distanceKm?: number }>; return demands.filter((d) => d.requesterId !== user.id).filter((d) => ['open', 'negotiating'].includes(d.status)).filter((d) => selectedTypeFilter === 'all' || d.type === selectedTypeFilter).filter((d) => !urgentOnly || d.isUrgent).map((d) => { const hasCoords = isValidCoordinates(providerLatitude, providerLongitude) && isValidCoordinates(d.latitude, d.longitude); return { demand: d, distanceKm: hasCoords ? distanceKm({ latitude: providerLatitude!, longitude: providerLongitude! }, { latitude: d.latitude!, longitude: d.longitude! }) : undefined }; }).filter((item) => item.distanceKm === undefined || item.distanceKm <= providerRadius).sort((a, b) => Boolean(b.demand.isUrgent) !== Boolean(a.demand.isUrgent) ? Number(Boolean(b.demand.isUrgent)) - Number(Boolean(a.demand.isUrgent)) : (a.distanceKm ?? Number.MAX_SAFE_INTEGER) - (b.distanceKm ?? Number.MAX_SAFE_INTEGER)); }, [demands, providerLatitude, providerLongitude, providerRadius, urgentOnly, selectedTypeFilter, user]);

  async function createLocalUser() { if (!name.trim()) return Alert.alert('Nome obrigatório', 'Informe seu nome para continuar.'); const newUser: User = { id: newId('usr'), name: name.trim(), role, serviceRadiusKm: role === 'provider' ? DEFAULT_RADIUS : undefined, createdAt: new Date().toISOString() }; await saveUser(newUser); setUser(newUser); setProviderRadius(newUser.serviceRadiusKm ?? DEFAULT_RADIUS); setProfileName(newUser.name); }
  async function captureLocationForDemand() { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return Alert.alert('Localização', 'Permissão não concedida. Informe o bairro/endereço manualmente.'); const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setLatitude(current.coords.latitude); setLongitude(current.coords.longitude); if (!locationLabel.trim()) setLocationLabel('Localização atual'); } catch { Alert.alert('Localização', 'Não foi possível obter sua localização.'); } }
  async function captureProviderLocation() { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return Alert.alert('Localização', 'Permissão não concedida.'); const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setProviderLatitude(current.coords.latitude); setProviderLongitude(current.coords.longitude); } catch { Alert.alert('Localização', 'Não foi possível obter sua localização.'); } }
  async function createDemand() { if (!user) return; const parsedBudget = budget.trim() ? Number(budget.replace(',', '.')) : undefined; if (!title.trim() || !description.trim() || !category || !locationLabel.trim()) return Alert.alert('Complete os dados', 'Preencha título, descrição, categoria e localização.'); if (parsedBudget !== undefined && (!Number.isFinite(parsedBudget) || parsedBudget <= 0)) return Alert.alert('Valor inválido', 'Informe um valor maior que zero ou deixe o campo vazio.'); const now = new Date().toISOString(); const next: Demand = { id: newId('dem'), requesterId: user.id, type, title: title.trim(), description: description.trim(), category, budgetType: parsedBudget ? 'fixed' : 'open', budget: parsedBudget, locationLabel: locationLabel.trim(), latitude, longitude, isUrgent, status: 'open', createdAt: now, updatedAt: now }; const nextDemands = [next, ...demands]; setDemands(nextDemands); await saveDemands(nextDemands); setTitle(''); setDescription(''); setBudget(''); setLocationLabel(''); setCategory(''); setLatitude(undefined); setLongitude(undefined); setIsUrgent(false); setScreen('home'); Alert.alert('Demanda publicada', isUrgent ? 'Sua demanda foi publicada como PRECISO AGORA.' : 'Sua demanda foi publicada.'); }
  async function ensureConversation(demandId: string, providerId: string) { if (!user) return null; const existing = conversations.find((item) => item.demandId === demandId && item.customerId === user.id && item.providerId === providerId); if (existing) return existing; const now = new Date().toISOString(); const conversation: Conversation = { id: newId('conv'), demandId, customerId: user.id, providerId, createdAt: now, updatedAt: now }; const next = [conversation, ...conversations]; setConversations(next); await saveConversations(next); return conversation; }
  async function openProposalChat(proposal: Proposal) { const demand = demands.find((item) => item.id === proposal.demandId); if (!demand) return; let conversation = conversations.find((item) => item.demandId === demand.id && item.customerId === demand.requesterId && item.providerId === proposal.providerId); if (!conversation) { const now = new Date().toISOString(); conversation = { id: newId('conv'), demandId: demand.id, customerId: demand.requesterId, providerId: proposal.providerId, createdAt: now, updatedAt: now }; const next = [conversation, ...conversations]; setConversations(next); await saveConversations(next); } setActiveConversation(conversation); setScreen('chat'); }
  async function submitProposal(demand: Demand) { if (!user) return; const amount = Number((proposalAmounts[demand.id] ?? '').replace(',', '.')); if (!Number.isFinite(amount) || amount <= 0) return Alert.alert('Valor inválido', 'Informe seu preço.'); if (proposals.some((item) => item.demandId === demand.id && item.providerId === user.id && item.status === 'pending')) return Alert.alert('Proposta já enviada', 'Você já possui uma proposta pendente para esta demanda.'); const now = new Date().toISOString(); const version = Math.max(0, ...proposals.filter((item) => item.demandId === demand.id).map((item) => item.version ?? 1)) + 1; const proposal: Proposal = { id: newId('pro'), demandId: demand.id, providerId: user.id, amount: Math.round(amount * 100) / 100, message: proposalMessages[demand.id]?.trim() || undefined, status: 'pending', version, offeredBy: 'provider', createdAt: now }; const nextProposals = [proposal, ...proposals]; const nextDemands = demands.map((item) => item.id === demand.id ? { ...item, status: 'negotiating' as const, updatedAt: now } : item); setProposals(nextProposals); setDemands(nextDemands); await saveProposals(nextProposals); await saveDemands(nextDemands); setProposalAmounts((state) => ({ ...state, [demand.id]: '' })); setProposalMessages((state) => ({ ...state, [demand.id]: '' })); Alert.alert('Proposta enviada', 'O cliente poderá negociar pelo chat.'); }
  async function acceptProposal(proposal: Proposal) { if (!user) return; const demand = demands.find((item) => item.id === proposal.demandId); if (!demand || demand.requesterId !== user.id || proposal.status !== 'pending') return; const now = new Date().toISOString(); const nextProposals = proposals.map((item) => item.demandId === demand.id ? { ...item, status: item.id === proposal.id ? ('accepted' as const) : item.status === 'pending' ? ('rejected' as const) : item.status } : item); const nextDemands = demands.map((item) => item.id === demand.id ? { ...item, status: 'accepted' as const, acceptedProviderId: proposal.providerId, updatedAt: now } : item); setProposals(nextProposals); setDemands(nextDemands); await saveProposals(nextProposals); await saveDemands(nextDemands); const conversation = await ensureConversation(demand.id, proposal.providerId); if (conversation) { setActiveConversation(conversation); setScreen('chat'); } }
  async function sendMessage(text: string) { if (!user || !activeConversation || !text.trim()) return; const message: ChatMessage = { id: newId('msg'), conversationId: activeConversation.id, senderId: user.id, text: text.trim(), createdAt: new Date().toISOString() }; const nextMessages = [...messages, message]; const nextConversations = conversations.map((item) => item.id === activeConversation.id ? { ...item, updatedAt: message.createdAt, lastMessageAt: message.createdAt } : item); setMessages(nextMessages); setConversations(nextConversations); await saveMessages(nextMessages); await saveConversations(nextConversations); }
  async function updateProviderSettings(radius: number) { if (!user) return; const nextUser = { ...user, serviceRadiusKm: radius }; await saveUser(nextUser); setUser(nextUser); setProviderRadius(radius); }
  async function updateProfileName() { if (!user || !profileName.trim()) return; const nextUser = { ...user, name: profileName.trim() }; await saveUser(nextUser); setUser(nextUser); }

  async function counterProposalFromChat(proposal: Proposal, amount: number, message?: string) { if (!user || proposal.status !== 'pending') return; const demand = demands.find((item) => item.id === proposal.demandId); if (!demand) throw new Error('Demanda não encontrada.'); const authorized = user.id === demand.requesterId || user.id === proposal.providerId; if (!authorized) throw new Error('Usuário sem permissão.'); const now = new Date().toISOString(); const nextVersion = Math.max(0, ...proposals.filter((item) => item.demandId === demand.id).map((item) => item.version ?? 1)) + 1; const counter: Proposal = { id: newId('pro'), demandId: demand.id, providerId: proposal.providerId, amount: Math.round(amount * 100) / 100, message, status: 'pending', version: nextVersion, parentProposalId: proposal.id, offeredBy: user.id === demand.requesterId ? 'customer' : 'provider', createdAt: now }; const nextProposals = proposals.map((item) => item.id === proposal.id && item.status === 'pending' ? { ...item, status: 'superseded' as const } : item); nextProposals.unshift(counter); const nextDemands = demands.map((item) => item.id === demand.id ? { ...item, status: 'negotiating' as const, updatedAt: now } : item); setProposals(nextProposals); setDemands(nextDemands); await saveProposals(nextProposals); await saveDemands(nextDemands); }

  async function confirmProviderAgreement(proposal: Proposal) { if (!user || user.id !== proposal.providerId || proposal.status !== 'accepted') throw new Error('Sem permissão.'); const now = new Date().toISOString(); const next = proposals.map((item) => item.id === proposal.id ? { ...item, providerConfirmedAt: now } : item); setProposals(next); await saveProposals(next); }
  async function startService(demand: Demand) { if (!user || user.id !== demand.acceptedProviderId || demand.status !== 'accepted') return; const now = new Date().toISOString(); const next = demands.map((item) => item.id === demand.id ? { ...item, status: 'in_progress' as const, startedAt: now, updatedAt: now } : item); setDemands(next); await saveDemands(next); }
  async function completeService(demand: Demand) { if (!user || user.id !== demand.acceptedProviderId || demand.status !== 'in_progress') return; const now = new Date().toISOString(); const next = demands.map((item) => item.id === demand.id ? { ...item, status: 'completed' as const, completedAt: now, updatedAt: now } : item); setDemands(next); await saveDemands(next); }

  if (!user) return <SafeAreaView style={styles.safe}><StatusBar style="light" /><ScrollView contentContainerStyle={styles.onboarding}><Text style={styles.logo}>Rubli</Text><Text style={styles.tagline}>Quem precisa, encontra quem resolve.</Text><Text style={styles.heading}>Crie seu perfil de teste</Text><Text style={styles.mutedLight}>Nesta fase, os dados ficam no aparelho. O MongoDB entra depois.</Text><TextInput value={name} onChangeText={setName} placeholder="Seu nome" placeholderTextColor="#718096" style={styles.inputDark} /><View style={styles.rowWrap}><RoleButton label="Quero contratar" active={role === 'customer'} onPress={() => setRole('customer')} /><RoleButton label="Quero trabalhar" active={role === 'provider'} onPress={() => setRole('provider')} /></View><TouchableOpacity style={styles.primaryButton} onPress={createLocalUser}><Text style={styles.primaryText}>Entrar no Rubli</Text></TouchableOpacity></ScrollView></SafeAreaView>;
  if (screen === 'chat' && activeConversation) return <ChatScreen conversation={activeConversation} currentUserId={user.id} messages={messages.filter((item) => item.conversationId === activeConversation.id).sort((a, b) => a.createdAt.localeCompare(b.createdAt))} onBack={() => setScreen('home')} onSend={sendMessage} onAcceptProposal={acceptProposal} onConfirmAgreement={confirmProviderAgreement} onCounterProposal={counterProposalFromChat} onStartService={startService} onCompleteService={completeService} />;

  return <SafeAreaView style={styles.safeLight}><StatusBar style="dark" /><View style={styles.header}><View><Text style={styles.brand}>Rubli</Text><Text style={styles.headerSubtitle}>Olá, {user.name}</Text></View><TouchableOpacity onPress={() => setScreen('profile')} style={styles.avatar}><Text style={styles.avatarText}>{user.name[0]?.toUpperCase()}</Text></TouchableOpacity></View>{screen === 'home' && user.role === 'customer' && <CustomerHome user={user} demands={demands} proposals={proposals} onCreate={(selectedType) => { setType(selectedType); setCategory(''); setScreen('create'); }} onAccept={acceptProposal} onChat={openProposalChat} onProfile={() => setScreen('profile')} />}{screen === 'home' && user.role === 'provider' && <ProviderHome user={user} feed={providerFeed} providerRadius={providerRadius} providerLatitude={providerLatitude} urgentOnly={urgentOnly} selectedTypeFilter={selectedTypeFilter} proposalAmounts={proposalAmounts} proposalMessages={proposalMessages} setUrgentOnly={setUrgentOnly} setSelectedTypeFilter={setSelectedTypeFilter} setProviderRadius={updateProviderSettings} onCaptureProviderLocation={captureProviderLocation} onProposal={submitProposal} onChat={openProposalChat} onProfile={() => setScreen('profile')} />}{screen === 'create' && <CreateDemand type={type} categories={categories} title={title} setTitle={setTitle} description={description} setDescription={setDescription} category={category} setCategory={setCategory} budget={budget} setBudget={setBudget} locationLabel={locationLabel} setLocationLabel={setLocationLabel} isUrgent={isUrgent} setIsUrgent={setIsUrgent} onCaptureLocation={captureLocationForDemand} onSubmit={createDemand} onBack={() => setScreen('home')} />}{screen === 'profile' && <Profile user={user} profileName={profileName} setProfileName={setProfileName} onSave={updateProfileName} onRadius={updateProviderSettings} radius={providerRadius} onBack={() => setScreen('home')} onNewTest={() => { saveUser(null); setUser(null); }} />}</SafeAreaView>;
}

function RoleButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={[styles.pill, active && styles.pillActive]}><Text style={[styles.pillText, active && styles.pillTextActive]}>{label}</Text></TouchableOpacity>; }
function ChatScreen({ conversation, currentUserId, messages, onBack, onSend, onAcceptProposal, onConfirmAgreement, onCounterProposal, onStartService, onCompleteService }: any) { return <View style={{ flex: 1 }}><Text>Use o ChatScreen do módulo src/screens/ChatScreen.tsx</Text></View>; }
function CustomerHome(_: any) { return <View><Text>Cliente</Text></View>; } function ProviderHome(_: any) { return <View><Text>Prestador</Text></View>; } function CreateDemand(_: any) { return <View><Text>Criar demanda</Text></View>; } function Profile(_: any) { return <View><Text>Perfil</Text></View>; }

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:BRAND},safeLight:{flex:1,backgroundColor:BG},onboarding:{flexGrow:1,padding:28,justifyContent:'center'},logo:{color:'#FFF',fontSize:42,fontWeight:'800',marginBottom:4},tagline:{color:'#DDE7F5',fontSize:16,marginBottom:42},heading:{color:'#FFF',fontSize:28,fontWeight:'800',marginBottom:10},mutedLight:{color:'#DDE7F5',lineHeight:20,marginBottom:18},inputDark:{backgroundColor:'#FFF',borderRadius:14,padding:16,marginBottom:14,fontSize:16},rowWrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:14},pill:{borderWidth:1,borderColor:'#CBD5E1',borderRadius:99,paddingHorizontal:13,paddingVertical:9,backgroundColor:'#FFF'},pillActive:{backgroundColor:BRAND,borderColor:BRAND},pillText:{color:'#526174',fontWeight:'600'},pillTextActive:{color:'#FFF'},primaryButton:{backgroundColor:ACCENT,borderRadius:14,padding:16,alignItems:'center',marginTop:6},primaryText:{color:'#FFF',fontSize:16,fontWeight:'800'},header:{backgroundColor:'#FFF',padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#E9EEF5'},brand:{color:BRAND,fontSize:25,fontWeight:'900'},headerSubtitle:{color:'#6B7788',marginTop:2},avatar:{width:42,height:42,borderRadius:21,backgroundColor:BRAND,alignItems:'center',justifyContent:'center'},avatarText:{color:'#FFF',fontWeight:'800'}});
