import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import type { Demand } from '@rubli/shared';
import { isValidCoordinates } from '@rubli/shared';

const BRAND = '#0B3B82';
const ACCENT = '#0B66FF';
const formatDistance = (km: number) => km < 1 ? `${Math.round(km * 1000)} m` : `${km.toFixed(1).replace('.', ',')} km`;
const typeLabel: Record<Demand['type'], string> = { service: 'Serviço', purchase: 'Compra', delivery: 'Entrega', freight: 'Frete' };

type Props = { feed: Array<{ demand: Demand; distanceKm?: number }>; latitude?: number; longitude?: number; onLocate: () => Promise<void>; onOpenOpportunity: (demand: Demand, distanceKm?: number) => void; };

/** Raiz da experiência do prestador. Feed e acesso à oportunidade ficam isolados do cliente. */
export function ProviderApp({ feed, latitude, longitude, onLocate, onOpenOpportunity }: Props) {
  if (!isValidCoordinates(latitude, longitude)) return <ScrollView contentContainerStyle={styles.content}><View style={styles.heroBox}><Text style={styles.hero}>Ative sua localização</Text><Text style={styles.muted}>Ela é obrigatória para mostrar chamados próximos e calcular a distância até cada cliente.</Text><TouchableOpacity style={styles.primary} onPress={onLocate}><Text style={styles.primaryText}>Usar minha localização</Text></TouchableOpacity></View></ScrollView>;
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.heroBox}><Text style={styles.hero}>Chamados próximos</Text><Text style={styles.muted}>Oportunidades organizadas automaticamente pela sua localização.</Text><TouchableOpacity style={styles.location} onPress={onLocate}><Text style={styles.locationText}>✓ Atualizar localização</Text></TouchableOpacity></View><Text style={styles.sectionTitle}>Demandas disponíveis</Text>{feed.length === 0 ? <Text style={styles.empty}>Não há chamados disponíveis próximos da sua localização agora.</Text> : feed.map(({ demand, distanceKm }) => <View style={styles.demand} key={demand.id}><View style={styles.demandTop}><Text style={styles.demandType}>{typeLabel[demand.type]}</Text><Text style={styles.distance}>{distanceKm === undefined ? 'Próximo' : formatDistance(distanceKm)}</Text></View>{demand.isUrgent && <Text style={styles.urgent}>⚡ PRECISO AGORA</Text>}<Text style={styles.demandTitle}>{demand.title}</Text><Text style={styles.mutedSmall}>{demand.category} · {demand.locationLabel}</Text><Text style={styles.mutedSmall}>{demand.description}</Text><Text style={styles.budget}>{demand.budget ? `Cliente informa: R$ ${demand.budget.toFixed(2).replace('.', ',')}` : 'Cliente deixou o valor aberto'}</Text><TouchableOpacity style={styles.viewButton} onPress={() => onOpenOpportunity(demand, distanceKm)}><Text style={styles.viewButtonText}>Ver chamado completo →</Text></TouchableOpacity></View>)}</ScrollView>;
}

const styles = StyleSheet.create({content:{padding:20,paddingBottom:96},heroBox:{backgroundColor:'#EAF1F8',borderRadius:18,padding:18,marginBottom:18},hero:{color:BRAND,fontSize:27,fontWeight:'800',marginBottom:6},muted:{color:'#68778C',lineHeight:20,marginBottom:12},primary:{backgroundColor:ACCENT,borderRadius:14,padding:16,alignItems:'center',marginTop:6},primaryText:{color:'#FFF',fontSize:16,fontWeight:'800'},location:{borderWidth:1,borderColor:'#AAB7C6',borderRadius:14,padding:14,alignItems:'center',marginBottom:8},locationText:{color:BRAND,fontWeight:'800'},sectionTitle:{color:BRAND,fontSize:20,fontWeight:'800',marginBottom:12,marginTop:6},empty:{color:'#718096',backgroundColor:'#FFF',padding:18,borderRadius:15,marginBottom:14},demand:{backgroundColor:'#FFF',borderRadius:16,padding:16,marginBottom:12,borderWidth:1,borderColor:'#E7ECF2'},demandTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:8},demandType:{color:ACCENT,fontWeight:'800'},distance:{color:BRAND,fontSize:12,fontWeight:'800'},urgent:{color:ACCENT,fontWeight:'900',marginBottom:7},demandTitle:{color:BRAND,fontSize:17,fontWeight:'800',marginBottom:6},mutedSmall:{color:'#68778C',lineHeight:19,marginBottom:7},budget:{color:'#465A73',fontWeight:'700',marginTop:2,marginBottom:9},viewButton:{borderWidth:1,borderColor:ACCENT,backgroundColor:'#EDF5FF',borderRadius:12,padding:12,alignItems:'center',marginBottom:10},viewButtonText:{color:ACCENT,fontWeight:'900'}});
